---
- name: lesson 3 3a
  hosts: cisco1:cisco2
  gather_facts: False
  tasks:
    - name: Show lldp
      cli_command:
        command: show lldp neighbors
      register: neighbors
      
      
    - name: Print lldp
      ansible.builtin.debug:
        var: neighbors["stdout_lines"]
        
    - name: Extract lines from output
      ansible.builtin.set_fact:
        lldp: " {{ neighbors["stdout_lines"] }} "
        
    - name: extract twb-sf-hpsw1
      ansible.builtin.set_fact:
        lldp_entry: " {{ item }} "
      loop: "{{ lldp }}"
      when: " 'twb-sf-hpsw1' in item "
        
    - name: Extract values
      ansible.builtin.set_fact:
        Remote_dev: " {{ lldp_entry.split()[0] }} "
        Local_intf: " {{ lldp_entry.split()[1] }} "
        Remote_Intf: " {{ lldp_entry.split()[-1] }} "
        
    - name: Display results
      ansible.builtin.debug:
        msg:
          - " Remote device: {{ Remote_dev }}  "
          - " Local intf: {{ Local_intf }} "
          - " Remote intf: {{ Remote_Intf }} "
