---
- name: lesson3 2a
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Find VLAN ID
      cli_command:
        command: show vlan id {{ item }}
      register: vlan
      loop:
        - 1
        - 2
        - 3
        - 4
        
        
 - name: Print value of vlan id 4
   ansible.builtin.debug:
     var: vlan["results'][3]["stdout_lines"]
     
     #vlan 4 is 3rd item in array
     # stdout_lines just displays to screen output of show vlan id 4
